# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=16)),
                ('expire_month', models.IntegerField()),
                ('expire_year', models.IntegerField()),
                ('cvv2', models.CharField(max_length=3)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('total', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
    ]
