# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(max_length=25)),
                ('alias', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=16)),
                ('expire_month', models.IntegerField()),
                ('expire_year', models.IntegerField()),
                ('cvv2', models.CharField(max_length=3)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('total', models.DecimalField(decimal_places=2, max_digits=7)),
                ('card_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pagos.CardType')),
            ],
        ),
        migrations.CreateModel(
            name='Donnor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('mail', models.EmailField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='Pago',
        ),
        migrations.AddField(
            model_name='donation',
            name='donnor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pagos.Donnor'),
        ),
    ]
